app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
dwr_open_weather:
    resource: "@DwrOpenWeatherBundle/Controller/"
    type:     annotation

pianosolo_weather:
    resource: "@PianoSoloWeatherBundle/Resources/config/routing.yml"
