# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # My services
    app.weatherHelper:
        class: AppBundle\Services\WeatherHelper
        arguments: ["%open_weather_api%"]
    app.newsHelper:
        class: AppBundle\Services\NewsHelper
        arguments: ["@doctrine.orm.entity_manager"]
